spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://nounou-db:5432/postgres
    driverClassName: org.h2.Driver
    password: nounou
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate

server:
  port: 8080



javamelody:
  init-parameters:
    log: true
    url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
    authorized-users: admin:pwd
    storage-directory: /tmp/javamelody
    monitoring-path: /monitoring
